apiVersion: v1
kind: Service
metadata:
  name: dir-monitor-svc
  namespace: dir-monitor
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    name: webui
    nodePort: 32078
  selector:
    app: dir-monitor
---
metadata:
  name: dir-monitor-deployment
  namespace: dir-monitor
  labels:
    app: dir-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dir-monitor
  template:
    metadata:
      labels:
        app: dir-monitor
    spec:
      containers:
      - name: dir-monitor
        image: ai-image.jd.com/ceph/dir-monitor:0.1
        imagePullPolicy: Always
        #        command: ["/bin/bash"]
        #        args:
        #        - "-c"
        #        - "go run *.go"
        #        #- "-m exporter"
        #        - "-c"
        #        - "汇天02"
        #        - "-p "
        #        - "/mnt/cephfs-ht01/algor-api/user/*/*,/mnt/cephfs-ht01/algor-api/dataset/user/*/*,/mnt/cephfs-ht01/algor-api/dataset/public/*"
        #        - "-NF"
        #        - "10000"
        #        - "-NB"
        #        - "1048576"
        ports:
        - containerPort: 8081
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 25
          periodSeconds: 20
        volumeMounts:
        - mountPath: "/mnt/cephfs"
          name: cephfs-ht02
        - mountPath: "/bin/getfattr"
          name: getfattr
        - mountPath: "/bin/setfattr"
          name: setfattr
      volumes:
      - name: cephfs-ht02
        cephfs:
          monitors:
          - 0.0.0.0
          user: admin
          secretRef:
            name: ceph-secret-admin
          readOnly: false
      - name: setfattr
        hostPath:
          path: /bin/setfattr
      - name: getfattr
        hostPath:
          path: /bin/getfattr
